### ISSUE TITLE
Questions about batch size.

### ISSUE THREAD

**Issue by D1aoBoomm** [tamertaras91/RR-CONV#1]
Hello,
I'm very interested in your novel work. 
However, I didn't find the batch size setting in the paper for the experiment. In the code, the batchsize seems to be 1. I wonder if the method can only be applied to scenarios where the batch size is 1?

**Comment by tamertaras91** [comment]
Hello 
Thank you for your interest.
Yes, only the batch of size one.

**Comment by D1aoBoomm** [comment]
Thank you for your answer!
I'm closing this issue.
